### ISSUE TITLE
Gnome 43 support

### ISSUE THREAD

**Issue by sidevesh** [Rafostar/gnome-shell-extension-pip-on-top#10]

**Comment by Rafostar** [comment]
Is this about something not working on GNOME 43 or to upload a version marked as 43 compatible to extensions website? I did not have time to test and upload it yet, but some time ago (43-beta) I heard it works without any changes.

**Comment by sidevesh** [comment]
Just uploading a version marked compatible, I have already made the change locally and it worked fine

**Comment by TheKrafter** [comment]
i would appreciate this too

**Comment by victante** [comment]
Can we help with testing or something for this? I'd love this extension on Gnome 43.

**Comment by Rafostar** [comment]
Now updated.
