### ISSUE TITLE
PIP window hides when using touchpad to change workspaces

### ISSUE THREAD

**Issue by IvoryJam** [Rafostar/gnome-shell-extension-pip-on-top#14]
If I use super+pgup/pgdown it comes works as expected.

If I change workspaces using the 3 finger swipe built into gnome it hides the window

Interestingly if I just use the 3 finger swipe to _almost_ change the workspace but don't, it still hides. Using the super+pgup/pgdown it comes back up.

**Comment by IvoryJam** [comment]
Info:
Fedora Linux 38 (Workstation Edition)
Gnome v44.2
Wayland

**Comment by IvoryJam** [comment]
Looks like it's a Gnome issue

**Comment by Rafostar** [comment]
@IvoryJam 

> Looks like it's a Gnome issue

Do you have a link to it?

**Comment by IvoryJam** [comment]
It looks like the issue was fixed in Gnome 44.4, I don't believe the bug was ever officially reported.

**Comment by osiride** [comment]
This still happens with Gnome 45.3.
