### ISSUE TITLE
Add GNOME 46 Support

### ISSUE THREAD

**Issue by andregarci** [Rafostar/gnome-shell-extension-pip-on-top#24]
It has just been updated to GNOME 46.0 and is not supported yet.

**Comment by Scotty-Trees** [comment]
Fedora 40 gets released tomorrow, hope this extension can get an update pushed within the first week, but no worries if it takes a little longer. This extension is just a must when you use Firefox on Wayland. Good luck!

**Comment by freundTech** [comment]
It looks like 46 support was already added in https://github.com/Rafostar/gnome-shell-extension-pip-on-top/pull/23, but the update hasn't been pushed to https://extensions.gnome.org yet.

You should be able to manually install using the instructions in the readme, or, if you already have the current version installed open `~/.local/share/gnome-shell/extensions/pip-on-top@rafostar.github.com/metadata.json` and change
```json
"shell-version": [
    "45"
  ],
  ```
  to 
  ```json
  "shell-version": [
    "45",
    "46"
  ],
  ```

**Comment by Rafostar** [comment]
Now on extensions website.
