### ISSUE TITLE
Please update for GNOME shell 46.1

### ISSUE THREAD

**Issue by lebensterben** [Rafostar/gnome-shell-extension-pip-on-top#25]
Thanks

**Comment by Rafostar** [comment]
@lebensterben 

Is there anything broken compared to 46 that an update is needed?

**Comment by lebensterben** [comment]
@Rafostar 

Sorry I haven't tested it. It's just that Gnome extension automatically disabled it because of version incompatibility.

**Comment by lebensterben** [comment]
@Rafostar 

I manually installed it and it works perfectly fine... But it's greyed out in Gnome Extensions and shows "OUTDATED" on https://extensions.gnome.org/extension/4691/pip-on-top/

**Comment by lebensterben** [comment]
It turns out that NixOS is shipping extension version 7. I'll close it here.
