### ISSUE TITLE
Add Gnome 47 Support

### ISSUE THREAD

**Issue by Scotty-Trees** [Rafostar/gnome-shell-extension-pip-on-top#27]
Gnome 47 has just been released! 

https://discourse.gnome.org/t/gnome-47-released/23398

https://release.gnome.org/47/

Please consider adding Gnome 47 support whenever you get around to it, thank you. Not too many big changes this time around, so hopefully fingers crossed it's a simple update for this lovely extension. Of course take all the time you need and thanks again for making it and hope to see it updated in the near future!

**Comment by Rafostar** [comment]
Updated version is now also available on GNOME extensions website.

**Comment by Scotty-Trees** [comment]
> Updated version is now also available on GNOME extensions website.

Thank you for taking care of this so quickly! Looking forward to using it on Fedora 41 once it’s released, thank you very much!
