### ISSUE TITLE
Feature Request: Always on Visible Workspace

### ISSUE THREAD

**Issue by maxlahn** [Rafostar/gnome-shell-extension-pip-on-top#5]
Thanks so much for this great and useful extension! If possible, it would be really nice to be able to configure the extension to also set picture-in-picture windows to be workspace-independent -- the desired functionality is currently obtained by clicking the "Always on Visible Workspace" button in the right-click menu of the picture-in-picture window.

**Comment by psydvl** [comment]
<details>
<summary>Just use <kbd>Win</kbd>+<kbd>Middle Mouse button</kbd> to open this  menu</summary>

![image](https://user-images.githubusercontent.com/43755002/175750509-5208f205-94f2-4477-8e20-609ec65fad93.png)

</details>

**Comment by Rafostar** [comment]
@psydvl 

OP already mentioned that he knows Super + Right click menu. It should be plausible to have this configurable as an option, so there is one less manual user action needed.

**Comment by psydvl** [comment]
Oh, sorry, missread then
Hmm, and <kbd>Win</kbd>+<kbd>Right click</kbd> allow you to resize any window instead of opening menu
While simple Right click pause Clapper for me

**Comment by Rafostar** [comment]
Added config option to show on all workspaces.

**Comment by maxlahn** [comment]
Thank you so much!
